# Generated by Django 4.1.6 on 2023-02-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0003_alter_category_name_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video',
            field=models.FileField(blank=True, upload_to='products_video/%Y/%m/%d', verbose_name='Видео'),
        ),
    ]
