# Generated by Django 4.1.6 on 2023-02-17 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0005_remove_product_image_productimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Фотография', 'verbose_name_plural': 'Фотографии'},
        ),
    ]
