# Generated by Django 4.1.6 on 2023-02-17 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0008_product_image_delete_productimage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='main_image',
        ),
    ]
