# Generated by Django 4.1.6 on 2023-02-17 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0009_rename_image_product_main_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='products_image/%Y/%m/%d', verbose_name='Фото'),
        ),
    ]
