# Generated by Django 4.1.6 on 2023-02-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shop', '0011_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='images',
        ),
        migrations.AddField(
            model_name='productimage',
            name='image',
            field=models.ImageField(default=1, upload_to='product_all_images/%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
